# Generated by Django 3.1.7 on 2021-05-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=250)),
                ('Phone_No', models.IntegerField(max_length=10)),
                ('Emailid', models.EmailField(max_length=254)),
            ],
        ),
    ]
