# Generated by Django 3.1.7 on 2021-05-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=250)),
                ('Phone_No', models.IntegerField(max_length=10)),
                ('Emailid', models.EmailField(max_length=254)),
                ('room_no', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
